name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      -  
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        #env:
         # TELETOK: ${{ secrets.TELETOK }}
        with:
          push: true
          tags: yuvenaliyt/clojure-auth-proxy-cache:latest
          secrets: 
            "TELETOK=${{ secrets.TELETOK }}"
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} 
      -  
        name: check teletok
        run: echo 1
